<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends \Doctrine\ORM\EntityRepository {

	public function findByBests(){

		$sql = "Select DISTINCT challenge.id From challenge " .
		"INNER JOIN user_challenge ON challenge.id = user_challenge.challenge_id " .
		"ORDER bY (Select count(*) from user_challenge " .
			"where user_challenge.challenge_id = challenge.id) DESC " .
"LIMIT 9";

			$stmt = $this->getEntityManager()
			->getConnection()
			->prepare($sql);
			$stmt->execute();
			$result = $stmt->fetchAll();

			return $result;
		}

		public function findByLowerId($id)
		{
			$sql = "SELECT DISTINCT c.id, c.creator_id, c.activity_id, c.title, c.creationDate, c.endDate " .
			"FROM challenge c ".
			"INNER JOIN user ON c.creator_id = user.id " .
			"WHERE c.id < $id " .
			"ORDER BY c.creationDate DESC " .
			"LIMIT 5";
			$stmt = $this->getEntityManager()
			->getConnection()
			->prepare($sql);
			$stmt->execute();
			$result = $stmt->fetchAll();
			return $result;
		}

}
