<?php

namespace AppBundle\Repository;

/**
 * DeviceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
