<?php

namespace AppBundle\Repository;

/**
 * PossessedDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossessedDeviceRepository extends \Doctrine\ORM\EntityRepository
{
/*    public function getDevice($id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder('d');
        $qb->select('*')
           ->from('deviceType')
           ->where('d.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }*/
}
