<?php

namespace AppBundle\Repository;

/**
 * PossessedDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossessedDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
