<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findBests(){
		$query = $this->getEntityManager()->getRepository('AppBundle:User')
		->createQueryBuilder('u')
	    ->orderBy('u.nbPoints', 'DESC')
	    ->getQuery();

		$users = $query->getResult();

		return $users;
	}
}
