<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * User_ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_ChallengeRepository extends EntityRepository
{
}
